#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: docker.pkg.github.com/cyberblack28/gitops-go-app
  tag: 14

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer
