#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: docker.pkg.github.com/cyberblack28/code/gitops-go-app
  tag: 16

imageConfig:
  pullPolicy: IfNotPresent

imageSecret:
  name: dockerconfigjson-github-com

#Service
service_type: ClusterIP
